Reworked CI step to exit on any error.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -15,4 +15,19 @@ jobs:
 
       - name: Run script unit tests
         run: |
-          find test -name test.sh -executable -print -execdir ./{} \;
+          set -e
+          WD=$(pwd)
+          TEST=$(find test -name test.sh -executable -print)
+          for file in $TEST; do
+            echo
+            echo "### Running $file ###"
+            echo
+            cd $(dirname $file)
+            if ! ./$(basename "$file"); then
+              echo "Error: Script $file failed!"
+              cd "$WD"
+              exit 1
+            fi
+
+            cd $WD
+          done
